name: Run automated tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy to ~/go/src
        run: mkdir -p ~/go/src/structuredhttp && cp -r . ~/go/src/structuredhttp && cd ~/go/src/structuredhttp

      - name: Run tests
        run: go test ./tests -v
